minecraft_version=1.21.8
minecraft_range=1.21.8
fabric_api_version=0.136.1+1.21.8
sodium_version=mc1.21.8-0.7.3-fabric
immediatelyfast_version=1.12.6+1.21.8-fabric
iris_version=1.9.6+1.21.8-fabric
sodium_min=0.7.0
sodium_recommended=0.7.3
java_release=21
layers=common,1.21.8+,1.21.x,1.21.8-1.21.10
modmenu_version=15.0.2
